version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload
    environment:
      SERPAPI_KEY: ${SERPAPI_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A app.tasks.celery_app worker --loglevel=info
    environment:
      SERPAPI_KEY: ${SERPAPI_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./app:/app/app
    depends_on:
      - redis
